apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  containers:
  - name: docker
    image: docker:latest
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
    - name: dockersock
      #mountPath: /var/run/docker.sock
      mountPath: /var/run
  volumes:
  - name: dockersock
    hostPath:
      #path: /var/run/docker.sock
      path: /var/run/dind/

