---
apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: website
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 2
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: how2die/website
        ports:
        - containerPort: 80
        imagePullPolicy: Always
